version: '3.8'

services:
    redis:
        image: redis:alpine
        ports: 
            - "6379:6379"
        restart: always
        
    node:
        build: ./runnershi
        restart: always
        links:
            - redis
        ports: 
            - 3000:3000

